server:
  port: 8054
spring:
  application:
    name: Knowledge_Hub_Portal
  datasource:
    url: jdbc:mysql://localhost:3306/com.knowledge_Hub?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
